name: Deploy Site on push
on:
  push:
    branches:
      - dev
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: 🔨 Build Project
        env:
          VITE_APP_PAYSTACK_PUBLIC_KEY: ${{ secrets.PAYSTACK_PUBLIC_KEY }}
          VITE_APP_API_URL: ${{ secrets.API_URL }}
        run: |
          yarn install
          yarn build

      - name: List output files
        run: find dist/ -print

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.LARAVEL_SITE_SERVER}}
          username: ${{ secrets.LARAVEL_SITE_USER}}
          password: ${{ secrets.LARAVEL_SITE_PASS}}
          server-dir: /public_html/
          local-dir: dist/
